### ISSUE TITLE
openBinaryFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by maghrab** [jtdaugherty/tart#4]
When trying to save the file and exit, I get the following error

openBinaryFile: does not exist (No such file or directory)

and I can't see the output files. Anything wrong with my build?

Thanks!

**Comment by jtdaugherty** [comment]
I can only reproduce that if the entered saving path is invalid (e.g. if I enter `foo/bar` and no directory `./foo` exists). Perhaps that's what happened in your case; otherwise saving should work just fine. At the very least `tart` doesn't handle that case well and should tell you that the path was invalid and let you correct it instead of crashing.
