### ISSUE TITLE
support brick-0.50

### ISSUE THREAD

**Issue by juhp** [jtdaugherty/tart#8]
No rush but it would be nice to allow building tart with newer versions of vty and brick.
Actually I would like to build it for distribution in Fedora.

**Comment by jtdaugherty** [comment]
Nice! Is the support for newer vty or brick versions required for distribution on Fedora? Or are those unrelated?

**Comment by jtdaugherty** [comment]
Also: it would be good to split up this request, because the tool `tart` requires `brick` but the library does not. And the library doesn't work with some older versions of `vty` if `ghc` is too new. So in other words, it would be super helpful if you can be more specific about which version(s) of the dependencies you'd like to use.

**Comment by juhp** [comment]
Okay I will file a separate bug for vty, thanks

**Comment by jtdaugherty** [comment]
As of yesterday, the tool now builds with brick 0.52 (only).

**Comment by juhp** [comment]
Thanks
